### ISSUE TITLE
users.py issue

### ISSUE THREAD

**Issue by guille-okt** [tuxudo/users#8]
users.py Error: Traceback (most recent call last):
    File "/usr/local/munkireport/scripts/users.py", line 228, in <module>
    main()
    File "/usr/local/munkireport/scripts/users.py", line 216, in main
    result = process_user_info(get_users_info(),get_group_names())
    File "/usr/local/munkireport/scripts/users.py", line 164, in process_user_info
    user_atts['copy_timestamp'] = str(time.mktime(datetime.strptime(user[user_att][0].strip(), "%Y-%m- 
    %dT%H:%M:%SZ").timetuple()))
    File "/Library/ManagedFrameworks/Python/Python3.framework/Versions/3.10/lib/python3.10/_strptime.py", line 568, in 
    _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    File "/Library/ManagedFrameworks/Python/Python3.framework/Versions/3.10/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
    ValueError: time data '-' does not match format '%Y-%m-%dT%H:%M:%SZ'
    WARNING: users.py return code: 1

**Comment by tuxudo** [comment]
Should be fixed in version v3.1 of the module.
